version: '3.9'

services:

  core.storage.secret.redis:
    container_name: core.storage.secret.redis
    image: redis:alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    command: "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - core.storage.secret.redis-data:/data
      - ./docker/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - core.storage.secret-network

  core.storage.secret.yopass:
    image: jhaals/yopass
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    command: "--metrics-port 999 --database redis --redis=redis://core.storage.secret.redis:6379/0 --port 80"
    ports:
      - 127.0.0.1:888:80
      - 127.0.0.1:999:999
    depends_on:
      - core.storage.secret.redis
    networks:
      - core.storage.secret-network

volumes:
  core.storage.secret.redis-data:
    driver: local

networks:
  core.storage.secret-network:
    name: core.storage.secret-network
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
